public class XversiLogComponent {

  public long boardFilled ;
  public long board ;
  public int bc ;
  public int wc ;
  public int side ;
  public int level ;
  public int score ;

  XversiLogComponent() { }

  XversiLogComponent(long bf , long b , int bcount , int wcount , int s , int l , int sc) {
    boardFilled = bf ;
    board = b ;
    bc = bcount ;
    wc = wcount ;
    side = s ;
    level = l ;
    score = sc ;

  }

}